Develop
AnnaYedoshina/QA24_TestRailDiploma_Yedoshina_Bobinin pull request #2
Opened 2023-07-21 16:26 UTC by AnnaYedoshina

2023-07-21 21:09 UTC, voropa requested changes

2023-07-21 21:09 UTC, voropa commented on src/test/java/api_tests/CasesApiTests.java
> +    private static final int PROJECT_ID = 8;
Вероятно вам не нужна эта константа PROJECT_ID, так как новый проект создается у вас в pre-conditions

2023-07-21 21:09 UTC, voropa commented on src/test/java/api_tests/CasesApiTests.java
> +    private static final int SUITE_ID = 2;
А почему SUITE_ID = 2  тут захардкодан?

2023-07-21 21:09 UTC, voropa commented on src/test/java/api_tests/CasesApiTests.java
> +                .statusCode(SC_OK);
А проверки где?

2023-07-21 21:09 UTC, voropa commented on src/test/java/api_tests/CasesApiTests.java
> +                .setEstimate("3m")
А чего только title и estimate заполняете, а остальные параметры где?

2023-07-21 21:09 UTC, voropa commented on src/test/java/api_tests/CasesApiTests.java
> +        int size = responseBody.getInt("size");
Интересный Assert, он проверяет, что actualResult = actualResult,  посмотрите внимательно

2023-07-21 21:09 UTC, voropa commented on src/test/java/api_tests/MilestoneApiTests.java
> +    private int projectId;
Зачем вам тут переменная projectId, она же уже есть в BaseApoiTest

2023-07-21 21:09 UTC, voropa commented on src/test/java/api_tests/MilestoneApiTests.java
> +                .pathParam("project_id", 7)
А тут projectId= 7 - хардкод

2023-07-21 21:09 UTC, voropa commented on src/test/java/api_tests/MilestoneApiTests.java
> +                .pathParam("project_id", 7)
и тут

2023-07-21 21:09 UTC, voropa commented on src/test/java/api_tests/MilestoneApiTests.java
> +                .pathParam("milestone_id", 5)
И тут хардкод. Предпполагаю, что API тесты вы еще будете переделывать с использованием контроллеров, так что обратите внимание на все эти id и другие хардкодные ппараметры

2023-07-21 21:09 UTC, voropa commented on src/test/java/api_tests/ProjectApiTests.java
> +    public void createProjectFromProject() {
Интересное название метода)

2023-07-21 21:09 UTC, voropa commented on src/test/java/controllers/ProjectController.java
> +    private final static String BASE_URL = "https://ibay.testrail.io/";
А зачем эти переменные тут? Они же у вас в BaseController есть

2023-07-21 21:09 UTC, voropa commented on src/test/java/models/ProjectResponse.java
> +public class ProjectResponse {
Этот класс у вас используется где-то?

2023-07-21 21:09 UTC, voropa commented on src/test/java/models/ProjectsResponse.java
> +public class ProjectsResponse {
и этот?

2023-07-21 21:09 UTC, voropa commented on src/test/java/pages/AddTestCasePage.java
> +    private By templateDropdownLocator = By.id("template_id_chzn");
Некрасиво получается, что у вас часть элементов тут обьявлена как String, а другие как By locator, сделайте одинаково. Они же все по id ищутся тут

2023-07-21 21:09 UTC, voropa commented on src/test/java/pages/AllProjectsPage.java
> +    String projectName = "TestProject";
Это что за хардкод внутри page класса? Удалите

2023-07-21 21:09 UTC, voropa commented on src/test/java/pages/AllProjectsPage.java
> +    public By projectLinkLocator = (By.xpath(String.format("//a[text() = '%s']", projectName)));
Странный локатор, это так не работает))

2023-07-21 21:09 UTC, voropa commented on src/test/java/pages/AllProjectsPage.java
> +    public By projectLinkLocator = (By.xpath(String.format("//a[text() = '%s']", projectName)));
У вас вместо лдокатора должна быть динамическая строка с парамметром, а птом уже в самом методе openProjectByName нужно подставлять туда название проекта. Посмотриите в проекте sauceDemo как мы это делали и сделайте по аналогии

2023-07-21 21:09 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    public String getErrorText() {
Очень схожие названия двух методов, как будто они одно и то же  сообщение должны получать, переименуйте

2023-07-21 21:09 UTC, voropa commented on src/test/java/pages/MilestonesPage.java
> +    public void deleteMilestone(Milestone milestone) {
Сюда можно String аргумент передавать, не обязательно целый обьект Milestone, вам же все равно из него только name нужен в мметоде

2023-07-21 21:09 UTC, voropa commented on src/test/java/pages/TestCaseInfoPage.java
> +    public TestCase getTestCaseInfo() {
Почем нет аннотации @Step

2023-07-21 21:09 UTC, voropa commented on src/test/java/pages/TestCaseInfoPage.java
> +                .setType(driver.findElement(By.id("cell_type_id")).getText().substring(5))
Не очень мне  нравится эта логика с substring() - не  надежно. Посмотрите в сторону String.split() и разбивайте текст по символу "/n", поотом берите вторую часть - так вроде надежнее

2023-07-21 21:09 UTC, voropa commented on src/test/java/tests/AddTestRunPageTests.java
> +    @Test
Выгляит как незавершенный тестовый сцеенарий

2023-07-21 21:09 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    protected final static String WRONG_USERNAME = "ayqa245@mailinator.com";
Зачем вам эти константы WRONG_USER / PASSWORD в BaseTets? Вы же их используете только в LoginTest - вот и храните их там. В baseTest иммет смысл выносить только те переменные ии методы, которые потом используютс я во многих / всех классах - наследникаах

2023-07-21 21:09 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    protected final static String NAME = "TestProject";
И тут еще в перемешку константы - переменные. Посмотрите java code convention и отформатируйте. Вроде порядод должен быть такой: константы -> public -> protected -> private ппеременные

2023-07-21 21:09 UTC, voropa commented on src/test/java/tests/LoginTests.java
> +    @Test(groups = {"smoke"}, description = "Негативное тестирование формы Login")
у 3х тестов подряд одинаковый description - плохо, он должен быть уникальным

2023-07-21 21:09 UTC, voropa commented on src/test/java/tests/MilestoneTests.java
> +        Assert.assertTrue(milestonesPage.isMilestoneAdded());
а проверить, что milestone с такими атрибутами присутвует после добавления?

2023-07-21 21:09 UTC, voropa commented on src/test/java/tests/MilestoneTests.java
> +
А тут где  проверки?

2023-07-21 21:09 UTC, voropa commented on src/test/java/tests/TestCasesTests.java
> +        Assert.assertTrue(testCasesPage.isCheckboxChecked());
Это не тесты)

2023-07-24 09:58 UTC, voropa requested changes

2023-07-24 09:58 UTC, voropa commented on pom.xml
> +        <dependency>
А зачем вам тут зависимость JUnit? мы же TestNg используем

2023-07-24 09:58 UTC, voropa commented on src/test/java/api_tests/BaseApiTest.java
>      protected static final String PASSWORD = System.getProperty("password", PropertyReader.getProperty("password"));
Нет смысла больше от этих констант в BaseApiTest, так как у вас вся настройока происхожит внутри контроллеров, а вы их тут используете

2023-07-24 09:58 UTC, voropa commented on src/test/java/api_tests/BaseApiTest.java
>                  .auth().preemptive().basic(USERNAME, PASSWORD)
И вот этот мметод setup() тоже больше не нужен, это все  в конструкторе baseController делается теперь

2023-07-24 09:58 UTC, voropa commented on src/test/java/api_tests/CasesApiTests.java
>          JsonPath responseBody = given()
Почему тут не используете casesController?

2023-07-24 09:58 UTC, voropa commented on src/test/java/api_tests/CasesApiTests.java
>                  .setEstimate("3m")
И тут тоже. 
Используйте контроллеры в тестах, чтобы выполнять запросы, собственно для этого их и вводили

2023-07-24 09:58 UTC, voropa commented on src/test/java/api_tests/MilestoneApiTests.java
>          Milestone expectedMilestone = Milestone.builder()
И тут, в тестах на milestones используйте milestoneController

2023-07-24 09:58 UTC, voropa commented on src/test/java/api_tests/ProjectApiTests.java
> +        Project projectToUpdate = Project.builder()
И тут контроллеры используйте

2023-07-24 09:58 UTC, voropa commented on src/test/java/controllers/BaseController.java
> +    public static final String BASE_URL_API = System.getenv().getOrDefault("TESTRAIL_API_URL",
Зачем эта перемменная BASE_URL_API, она вроде нигде не используется потом

2023-07-24 09:58 UTC, voropa commented on src/test/java/controllers/MilestoneController.java
> +                .statusCode(200)
Со статус кодами сделайте везде  одинаково: либо во всех методах всех контроллеров из добавьте, либо везде уберите и проверяйте статус коды в тестах потом отдельно. А то сейчас они в половине методов у вас есть, а в части  - нет

2023-07-24 09:58 UTC, voropa commented on src/test/java/pages/AllProjectsPage.java
> +    public By projectLinkLocator = (By.xpath(String.format("//a[text() = '%s'")));
Вот тут у вас должно быть обьявлено private String projectLinkLocator = "a[text()='%s']";
потом в метрод openProjectByName(String name) {
driver.findElemnt(By.xpath(String.format(projectLinkLocator, name)))
}

2023-07-25 08:47 UTC, AnnaYedoshina commented on src/test/java/api_tests/BaseApiTest.java
>      protected static final String PASSWORD = System.getProperty("password", PropertyReader.getProperty("password"));
Так а в методе setUp они же используются

2023-07-25 08:47 UTC, AnnaYedoshina commented on src/test/java/api_tests/BaseApiTest.java
>                  .auth().preemptive().basic(USERNAME, PASSWORD)
ой, поняла)

2023-07-25 14:41 UTC, merged